default:
  workspace: shared
  
.skip-deploy: &skip-deploy
  messages:
  - '[ci skip deploy]'


stages:
- Install
- Build
- Test

jobs:
- name: Yarn Install
  image: node:12-alpine
  stage: Install
  script:
  - echo "yarn install"

- name: Sleep
  stage: Build
  image: alpine
  script:
  - sleep 10
  - echo $CI_COMMIT_MESSAGE
  except:
    <<: *skip-deploy

- name: Say bye!
  stage: Test
  image: alpine
  workspace: none
  script:
  - sleep 10
  - echo Byeee!

- name: Say bye again!
  stage: Test
  image: alpine
  script:
  - sleep 10
  - echo Byeee!
